# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f7b2796488e9eea9e8af723590e9ad391b42b5dbb146a5d44aebbcbed952f1267f640bebf97e2bc3614eb61fdf50c6fea5a4490ee71668880b7c9bf30087d02

test:
  secret_key_base: 4a4a78e230cc4f7cc4ca1742fe08601f1c014fae78d31a78c0ca31a1014798ead308399df2e19017151b613bc085ddeacdb107e01b83bbf83be875d3edd442a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
